CREATE TABLE atms
(
    id       BIGINT AUTO_INCREMENT NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_atms PRIMARY KEY (id)
);

ALTER TABLE atms
    ADD CONSTRAINT uc_atms_username UNIQUE (username);

create table cards
(
    id       bigint generated by default as identity,
    balance  bigint,
    number   bigint,
    pin integer,
    primary key (id)
)